### PR TITLE
Update to spec 9230

### PR DESCRIPTION
**Pull request by ftheirs**
Implement Crowdloan pallet

### CODE REVIEW

**Comment by carlosala** [comment]
Hi! We also bundled in this PR the upgrade to spec 9220, and also other minor changes. Thanks!

**Comment by lpascal-ledger** [comment]
@ftheirs Could you please update this branch up to the base branch, and enable the CI on `develop` (currently `main` only)?
Thanks

**Comment by carlosala** [comment]
Sure! I'll take care of that!

**Comment by carlosala** [comment]
@lpascal-ledger I have done that and enabled ci at develop branch. I also updated the submodules so we can also install that with our installer to LNS+ v1.0.3 firmware version. There are no changes on the source side.
By the way, I see that your `main` and `develop` branches don't have merge conflicts with our PR, I don't see why should update the branch. Get back to me so I can understand that!

**Comment by carlosala** [comment]
By the way! Could you rename `master` branch to `main` in https://github.com/ledgerHQ/app-kusama? I see that the CI is not running there for that reason 👍🏻

**Comment by lpascal-ledger** [comment]
Thanks @carlosala
Good catch for the submodules, I always forget to check them when present as I always use the latest docker image which keeps the SDK up to date.
Indeed their were no conflict, but the "Require branches to be up to date before merging" option was checked on `develop` branch protection, blocking the merge. Not on `main` though - so I unchecked it.

**Comment by carlosala** [comment]
Nice! I'm going to send a super similar PR for kusama, so we enable also CI in develop, updates submodules and all the stuff :)
Thanks @lpascal-ledger

**Comment by lpascal-ledger** [comment]
@carlosala Also could you please add a `pull_request` trigger on `main` & `develop` for the `.github/workflows/main.yml` workflow? With push only it does not seem to be displayed on the PR checks.

**Comment by lpascal-ledger** [comment]
@carlosala Indeed as the PR comes from your `main`. Alright, I'll keep it here. :+1:

**Comment by carlosala** [comment]
Thanks @lpascal-ledger! You have the kusama PR also opened :)

**Pull request merged**
